---
project:
  type: website

website:
  title: "Mitt prosjekt"
  navbar:
    left:
      - href: index.qmd
        text: Hjem

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    number-sections: true
    self-contained: true
---
