name: Quarto Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install system libraries (sf/geo + graphics)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libudunits2-dev libgdal-dev libgeos-dev libproj-dev \
            libfontconfig1-dev libharfbuzz-dev libfribidi-dev \
            libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::knitr
            any::rmarkdown
            any::readr
            any::dplyr
            any::tidyr
            any::tibble
            any::stringr
            any::purrr
            any::ggplot2
            any::scales
            any::lubridate
            any::janitor
            any::here
            any::glue
            any::sf
            any::rnaturalearth
            any::rnaturalearthdata

      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false

      - uses: quarto-dev/quarto-actions/render@v2

      - uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
